title: "my blog page"
theme: minima
author: TZS
email: 1155141394@link.cuhk.edu.hk
description: > # this means to ignore newlines until "baseurl:"
  hahahaha

# social links
twitter_username: UNKNOWN # DO NOT include the @ character, or else the build will fail!
github_username:  1155141394 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
